- hosts: docker_hosts
  sudo: yes

  tasks:

      # This playbook will only work on Ubuntu servers because it uses "apt"
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install pip
      apt:
        name: python-pip
        state: present

      # Install docker
    - include: install-docker.yml

    - name: run page-hit-counter-redis
      docker:
        docker_api_version: "1.18"
        image: redis:3
        state: started
        pull: "always"
        name: page-hit-counter-redis

    - name: run page-hit-counter-app
      docker:
        docker_api_version: "1.18"
        image: "<< your registry here >>/page-hit-counter"
        ports:
        - "80:5000"
        links:
        - "page-hit-counter-redis:redis"
        state: reloaded
        pull: "always"
        registry: "<< your registry here >>"
        username: "<< your username here >>"
        email: "<< your email here >>"
        password: "<< your password here >>"
        name: page-hit-counter-app
