---

- name: Ensure docker apt key is up to date
  apt_key:
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    id: "58118E89F3A912897C070ADBF76221572C52609D"

- name: Ensure repo definition is up to date
  template:
    src: docker.sources.list
    dest: /etc/apt/sources.list.d/docker.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Ensure docker-engine is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - "apt-transport-https"
  - "ca-certificates"
  - "docker-engine"

- name: Ensure the docker daemon is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Install docker-py
  pip:
    name: docker-py
    version: 1.8.1